version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: Pooja@2000
      MYSQL_DATABASE: banking_db
    ports:
      - "3307:3306"
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  banking-service:
    image: banking-service:latest
    container_name: banking-service
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8585:8585"
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8585/health"]  # Replace with actual health endpoint
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  transaction-service:
    image: transaction-service:latest
    container_name: transaction-service
    depends_on:
      banking-service:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql-container
      MYSQL_PORT: 3306
      MYSQL_DB_NAME: banking_db
      MYSQL_USER: root
      MYSQL_PASSWORD: Pooja@2000
    ports:
      - "8484:8484"
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8484/health"]  # Replace with actual health endpoint
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

networks:
  my-network:
    driver: bridge
